dist: bionic
language: node_js
node_js: 12
cache:
  yarn: true
  directories:
    - node_modules
    - docs/.cache
    - docs/node_modules
    - docs/public

jobs:
  include:
    - stage: Tests & Code Check
      name: '[Chromium] Functional Tests'
      # https://github.com/microsoft/playwright/issues/581
      before_script: node ./node_modules/playwright/install.js
      script: BROWSER=chromium yarn test:functional

    - stage: Tests & Code Check
      name: '[Firefox] Functional Tests'
      # https://github.com/microsoft/playwright/issues/581
      before_script: node ./node_modules/playwright/install.js
      script: BROWSER=firefox yarn test:functional

    - stage: Tests & Code Check
      name: '[WebKit] Functional Tests'
      # https://github.com/microsoft/playwright/issues/581
      before_script: node ./node_modules/playwright/install.js
      script: BROWSER=webkit yarn test:functional

    - stage: Deploy
      name: Website / Documentation
      if: '(NOT type IN (pull_request)) AND (branch = master)'
      script:
        - yarn build
        - cd docs
        - yarn install
        - yarn deploy
