name: Functional Tests

on: [push]

jobs:
  functional-chromium:
    name: Chromium Functional Tests
    runs-on: ubuntu-latest
    container:
      image: arjun27/playwright-bionic:0.1.1
    steps:
      - run: npm i -g yarn
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: node ./node_modules/playwright/install.js
      - run: yarn test:functional
        env:
          BROWSER: chromium
          CI: true

  functional-firefox:
    name: Firefox Functional Tests
    runs-on: ubuntu-latest
    container:
      image: arjun27/playwright-bionic:0.1.1
    steps:
      - run: npm i -g yarn
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: node ./node_modules/playwright/install.js
      - run: yarn test:functional
        env:
          BROWSER: firefox
          CI: true

  functional-webkit:
    name: WebKit Functional Tests
    runs-on: ubuntu-latest
    container:
      image: arjun27/playwright-bionic:0.1.1
    steps:
      - run: npm i -g yarn
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: node ./node_modules/playwright/install.js
      - run: yarn test:functional
        env:
          BROWSER: webkit
          CI: true
